apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
  labels:
    app: frontend
    environment: dev
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: platform-deploys
spec:
  project: gitops-platform

  source:
    repoURL: https://github.com/YOUR_ORG/gke-gitops-platform.git
    targetRevision: main
    path: k8s/overlays/dev
    kustomize:
      namePrefix: ""

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

  # Health checks
  ignoreDifferences:
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/metrics
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-staging
  namespace: argocd
  labels:
    app: frontend
    environment: staging
spec:
  project: gitops-platform

  source:
    repoURL: https://github.com/YOUR_ORG/gke-gitops-platform.git
    targetRevision: main
    path: k8s/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod
  namespace: argocd
  labels:
    app: frontend
    environment: production
spec:
  project: gitops-platform

  source:
    repoURL: https://github.com/YOUR_ORG/gke-gitops-platform.git
    targetRevision: main
    path: k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  # Production: manual sync required
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
