# ArgoCD Application for monitoring resources (ServiceMonitor, etc.)
# Watches k8s/overlays/dev via Kustomize
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jithin2/gke-gitops-platform.git
    targetRevision: main
    path: k8s/overlays/dev

    # Kustomize — no extra config needed, ArgoCD auto-detects kustomization.yaml
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
